@baseUrl = http://localhost:2000/api
@email = test@test.com
@password = test1234

# --- USER AUTHENTICATION ---

### @name signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### @name validateToken
@token = {{login.response.body.token}}
GET {{baseUrl}}/users/validate
Authorization: Bearer {{token}}

# --- PRODUCT ROUTER ---

### @name getProducts
@token = {{login.response.body.token}}
GET {{baseUrl}}/products
Authorization: Bearer {{token}}

### @name getProductByCategory
@token = {{login.response.body.token}}
GET {{baseUrl}}/products?category=electronics
Authorization: Bearer {{token}}

# --- ORDER ROUTER ---


### @name createOrder
@token = {{login.response.body.token}}
POST {{baseUrl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    { "productId": 1, "quantity": 2 },
    { "productId": 2, "quantity": 1 }
  ]
}

### @name getOrders
@token = {{login.response.body.token}}
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}
