{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "postgres", "query": { "query": "label_names()" } },
   { "name": "backend", "query": { "query": "label_names()" } },
   { "name": "frontend", "query": { "query": "label_names()" } }
  ]
 },
 "panels": [
  { "title": "Per Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Pods UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{deployment=\"backend\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"backend\"})",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Backend CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg by () (rate(container_cpu_usage_seconds_total{pod=~\"$backend\"}[2m])) / avg by () (kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$backend\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "100 * max by () (rate(container_cpu_usage_seconds_total{pod=~\"$backend\", container!=\"POD\"}[2m])) / avg by () ( kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$backend\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Backend RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nmax by () (\n  container_memory_working_set_bytes{\n    pod=~\"$backend\",\n    container!=\"POD\"\n  }\n)\n/\navg by () (\n  kube_pod_container_resource_requests{\n    resource=\"memory\",\n    pod=~\"$backend\"\n  }\n)",
     "legendFormat": "AVG"
    },
    {
     "expr": "100 *\navg by () (\n  container_memory_working_set_bytes{\n    pod=~\"$backend\",\n    container!=\"POD\"\n  }\n)\n/\navg by () (\n  kube_pod_container_resource_requests{\n    resource=\"memory\",\n    pod=~\"$backend\"\n  }\n)",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Frontend Pods UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{deployment=\"frontend\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"frontend\"})",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Frontend CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg by () (rate(container_cpu_usage_seconds_total{pod=~\"$frontend\"}[2m])) / avg by () (kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$frontend\"})",
     "legendFormat": "AVG"
    },
    {
     "expr": "100 * max by () (rate(container_cpu_usage_seconds_total{pod=~\"$frontend\", container!=\"POD\"}[2m])) / avg by () ( kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$frontend\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Frontend RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nmax by () (\n  container_memory_working_set_bytes{\n    pod=~\"$frontend\",\n    container!=\"POD\"\n  }\n)\n/\navg by () (\n  kube_pod_container_resource_requests{\n    resource=\"memory\",\n    pod=~\"$frontend\"\n  }\n)",
     "legendFormat": "AVG"
    },
    {
     "expr": "100 *\navg by () (\n  container_memory_working_set_bytes{\n    pod=~\"$frontend\",\n    container!=\"POD\"\n  }\n)\n/\navg by () (\n  kube_pod_container_resource_requests{\n    resource=\"memory\",\n    pod=~\"$frontend\"\n  }\n)",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Database Pods UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"postgres\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=\"postgres\"})",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Database CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mc" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{pod=~\"$postgres\"}[2m])\n) * 1000\n",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Database RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{pod=~\"$postgres\"}\n)\n",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Database Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_database_size_bytes{datname=\"dev\"})",
     "legendFormat": "Storage"
    },
    {
     "expr": "max(pg_database_size_bytes{datname=\"dev\"}) / max(kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=\"postgres-pvc\"}) * 100",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Backend Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (status_code) (increase(http_errors_total{status_code!~\"2..\"}[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (route) (increase(http_requests_total{route!~\"/api/uploads.*|/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API Reponse Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{route!~\"(/api/uploads.*|/metrics)\"}[2m])) by (route)\n/\nsum(rate(http_request_duration_seconds_count{route!~\"(/api/uploads.*|/metrics)\"}[2m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(login_attempts_total{success=\"false\"}[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(login_attempts_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Error 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status_code=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors by Route",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_errors_total[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_errors_total[1m]))\n/\nsum(increase(http_requests_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Login Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(login_attempts_total{success=\"false\"}[1m])) / sum(increase(login_attempts_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Kubernetes CPU Usage %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n  sum(rate(container_cpu_usage_seconds_total[5m]))\n/\n  sum(kube_node_status_capacity{resource=\"cpu\"})\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Memory Usage %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n  sum(container_memory_working_set_bytes)\n/\n  sum(kube_node_status_capacity{resource=\"memory\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Rollout Progress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_deployment_status_replicas_updated[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[1h])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 44 },
   "targets": [
    { "expr": "avg(node_load1)\n", "legendFormat": "__auto" },
    { "expr": "avg(node_load5)\n", "legendFormat": "__auto" },
    { "expr": "avg(node_load15)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kube API Server Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (verb)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total database queries",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db_queries_total{success=\"true\"}[1m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(db_query_duration_seconds_sum[2m])) by (operation) / sum(rate(db_query_duration_seconds_count[2m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks & Conflicts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pg_stat_database_deadlocks[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db_queries_total{success=\"false\"}[2m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Query Duration (P99 Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_query_duration_seconds_bucket[2m])) by (operation, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit[5m])) \n/ \n(sum(rate(pg_stat_database_blks_hit[5m])) + sum(rate(pg_stat_database_blks_read[5m]))) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connection usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"}) / sum(pg_settings_max_connections) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection State Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuple Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched[5m])) / sum(rate(pg_stat_database_tup_returned[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Backend Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({service_name=\"backend\"} |= \"ERROR\")[5m]))"
    }
   ]
  },
  {
   "title": "Frontend Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({service_name=\"frontend\"} |= \"ERROR\")[5m]))"
    }
   ]
  },
  {
   "title": "Postgres Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({service_name=\"postgres\"} |= \"ERROR\")[5m]))"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"backend\"}"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Postgres Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"postgres\"}"
    }
   ]
  }
 ]
}