apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: nginx-gateway
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app-gateway-nginx
    app.kubernetes.io/instance: ngf
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32003
